name: Compil

on: [push, pull_request]

jobs:
  windows-compil:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install winget
        uses: Cyberboss/install-winget@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          winget install --accept-package-agreements --accept-source-agreements CMake
          winget install --accept-package-agreements --accept-source-agreements LLVM

      - name: Compil
        run: ./scripts/compil.ps1 --dry-run

  linux-compil:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y g++ cmake clang-tidy libxrandr-dev

      - name: Compil
        run: ./scripts/compil.sh --dry-run

  macos-compil:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install cmake
          brew install llvm
          ln -s "$(brew --prefix llvm)/bin/clang-tidy" "/usr/local/bin/clang-tidy"

      - name: Compil
        run: ./scripts/compil.sh --dry-run
