name: Documentation
on:
  push:
    branches: [main, dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch 
      pages: write  # To push to a GitHub Pages site
      id-token: write # To update the deployment status

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check modified files need re run
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            docs:
              - 'docs/**'

      - name: Install latest mdbook
        if: steps.filter.outputs.docs == 'true' || github.ref == 'refs/heads/dev'
        run: |
          tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
          url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir mdbook
          curl -sSL $url | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH

      - name: Build Book
        if: steps.filter.outputs.docs == 'true' || github.ref == 'refs/heads/dev'
        run: mdbook build

      - name: Setup Pages
        if: steps.filter.outputs.docs == 'true'
        uses: actions/configure-pages@v3

      - name: Upload artifact
        if: steps.filter.outputs.docs == 'true'
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: 'book'

      - name: Deploy to GitHub Pages
        if: steps.filter.outputs.docs == 'true'
        id: deployment
        uses: actions/deploy-pages@v2
