name: Format

on: [push, pull_request]

jobs:
  windows-format:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install winget
        uses: Cyberboss/install-winget@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: winget install --accept-package-agreements --accept-source-agreements LLVM

      - name: Format
        run: ./scripts/format.ps1 --dry-run

  linux-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get -y install clang

      - name: Format
        run: ./scripts/format.sh --dry-run

  macos-format:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install clang-format

      - name: Format
        run: ./scripts/format.sh --dry-run
