name: Format

on: [push, pull_request]

jobs:
  # windows-format:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #
  #     - name: Install winget
  #       uses: Cyberboss/install-winget@v1
  #       with:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #
  #     - name: Install dependencies
  #       run: ./scripts/install-deps-windows.ps1
  #
  #     - name: Format
  #       run: ./scripts/format.ps1 --dry-run
  #
  # linux-format:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #
  #     - name: Install dependencies
  #       run: sudo ./scripts/install-deps-linux.sh
  #
  #     - name: Format
  #       run: ./scripts/format.sh --dry-run
  #
  # macos-format:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #
  #     - name: Install dependencies
  #       run: ./scripts/install-deps-macos.sh
  #
  #     - name: Format
  #       run: ./scripts/format.sh --dry-run

  auto-format:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository && github.event_name == 'pull_request' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set safe git
        run: git config --global --add safe.directory $(pwd)

      - name: Install dependencies
        run: sudo ./scripts/install-deps-linux.sh

      - name: Format
        run: ./scripts/format.sh

      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT

      - name: Show modified
        run: git diff

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git commit -am "FORMAT-AUTO: automatic format on pull request #${{ github.event.number }}"
          git push
